apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      name: api
      protocol: TCP
      targetPort: api
      nodePort: 30900
    - port: 9090
      name: console
      protocol: TCP
      targetPort: console
      nodePort: 30990
