apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
commonLabels:
  app: minio
resources:
- deployment.yaml
- namespace.yaml
- pvc.yaml
- service.yaml

secretGenerator:
  - name: minio-creds
    envs:
      - secrets/minio-creds.env
