apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - port: 9000
      name: api
      protocol: TCP
      targetPort: api
    - port: 9090
      name: console
      protocol: TCP
      targetPort: console
